# app/config/routing.yml
circuit:
    resource: "@CircuitBundle/Resources/config/routing.yml"
    prefix:   /

progression:
    resource: "@ProgressionBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_login:
    path:    /user/login
    defaults: { _controller: AppBundle:Security:login}

user_login_check:
    path:    /user/login/check
    defaults: { _controller: AppBundle:Security:check}

homepage:
    path:    /
    defaults: { _controller: AppBundle:Default:index}