<?php

namespace ProgressionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * progressionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class progressionRepository extends EntityRepository
{
}
